/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as DashboardIntegrationsRouteImport } from './routes/_dashboard/integrations'
import { Route as DashboardDevicesRouteImport } from './routes/_dashboard/devices'
import { Route as DashboardDeviceRouteImport } from './routes/_dashboard/device'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as DashboardReposSlugRouteImport } from './routes/_dashboard/repos/$slug'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIntegrationsRoute = DashboardIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDevicesRoute = DashboardDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDeviceRoute = DashboardDeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardReposSlugRoute = DashboardReposSlugRouteImport.update({
  id: '/repos/$slug',
  path: '/repos/$slug',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/welcome': typeof WelcomeRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/device': typeof DashboardDeviceRoute
  '/devices': typeof DashboardDevicesRoute
  '/integrations': typeof DashboardIntegrationsRoute
  '/settings': typeof DashboardSettingsRoute
  '/repos/$slug': typeof DashboardReposSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/welcome': typeof WelcomeRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/device': typeof DashboardDeviceRoute
  '/devices': typeof DashboardDevicesRoute
  '/integrations': typeof DashboardIntegrationsRoute
  '/settings': typeof DashboardSettingsRoute
  '/repos/$slug': typeof DashboardReposSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/home': typeof HomeRoute
  '/welcome': typeof WelcomeRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/device': typeof DashboardDeviceRoute
  '/_dashboard/devices': typeof DashboardDevicesRoute
  '/_dashboard/integrations': typeof DashboardIntegrationsRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/repos/$slug': typeof DashboardReposSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/welcome'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/device'
    | '/devices'
    | '/integrations'
    | '/settings'
    | '/repos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/welcome'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/device'
    | '/devices'
    | '/integrations'
    | '/settings'
    | '/repos/$slug'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_dashboard'
    | '/home'
    | '/welcome'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_dashboard/dashboard'
    | '/_dashboard/device'
    | '/_dashboard/devices'
    | '/_dashboard/integrations'
    | '/_dashboard/settings'
    | '/_dashboard/repos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  HomeRoute: typeof HomeRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/integrations': {
      id: '/_dashboard/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof DashboardIntegrationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/devices': {
      id: '/_dashboard/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DashboardDevicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/device': {
      id: '/_dashboard/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DashboardDeviceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dashboard/repos/$slug': {
      id: '/_dashboard/repos/$slug'
      path: '/repos/$slug'
      fullPath: '/repos/$slug'
      preLoaderRoute: typeof DashboardReposSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardDeviceRoute: typeof DashboardDeviceRoute
  DashboardDevicesRoute: typeof DashboardDevicesRoute
  DashboardIntegrationsRoute: typeof DashboardIntegrationsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardReposSlugRoute: typeof DashboardReposSlugRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardDeviceRoute: DashboardDeviceRoute,
  DashboardDevicesRoute: DashboardDevicesRoute,
  DashboardIntegrationsRoute: DashboardIntegrationsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardReposSlugRoute: DashboardReposSlugRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  HomeRoute: HomeRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
