/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OgRouteImport } from './routes/og'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ExtensionRouteImport } from './routes/extension'
import { Route as AnimationRouteImport } from './routes/animation'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogIntroducingEnvvalRouteImport } from './routes/blog/introducing-envval'
import { Route as MarketingTermsRouteImport } from './routes/_marketing/terms'
import { Route as MarketingSecurityRouteImport } from './routes/_marketing/security'
import { Route as MarketingPrivacyRouteImport } from './routes/_marketing/privacy'
import { Route as MarketingCookiePolicyRouteImport } from './routes/_marketing/cookie-policy'
import { Route as MarketingContactRouteImport } from './routes/_marketing/contact'
import { Route as MarketingChangelogRouteImport } from './routes/_marketing/changelog'
import { Route as MarketingAboutRouteImport } from './routes/_marketing/about'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as DashboardIntegrationsRouteImport } from './routes/_dashboard/integrations'
import { Route as DashboardDevicesRouteImport } from './routes/_dashboard/devices'
import { Route as DashboardDeviceRouteImport } from './routes/_dashboard/device'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as DashboardReposSlugRouteImport } from './routes/_dashboard/repos/$slug'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OgRoute = OgRouteImport.update({
  id: '/og',
  path: '/og',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionRoute = ExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimationRoute = AnimationRouteImport.update({
  id: '/animation',
  path: '/animation',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIntroducingEnvvalRoute = BlogIntroducingEnvvalRouteImport.update({
  id: '/blog/introducing-envval',
  path: '/blog/introducing-envval',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingTermsRoute = MarketingTermsRouteImport.update({
  id: '/_marketing/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingSecurityRoute = MarketingSecurityRouteImport.update({
  id: '/_marketing/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingPrivacyRoute = MarketingPrivacyRouteImport.update({
  id: '/_marketing/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingCookiePolicyRoute = MarketingCookiePolicyRouteImport.update({
  id: '/_marketing/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingContactRoute = MarketingContactRouteImport.update({
  id: '/_marketing/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingChangelogRoute = MarketingChangelogRouteImport.update({
  id: '/_marketing/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/_marketing/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIntegrationsRoute = DashboardIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDevicesRoute = DashboardDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDeviceRoute = DashboardDeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardReposSlugRoute = DashboardReposSlugRouteImport.update({
  id: '/repos/$slug',
  path: '/repos/$slug',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/animation': typeof AnimationRoute
  '/extension': typeof ExtensionRoute
  '/home': typeof HomeRoute
  '/og': typeof OgRoute
  '/onboarding': typeof OnboardingRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/device': typeof DashboardDeviceRoute
  '/devices': typeof DashboardDevicesRoute
  '/integrations': typeof DashboardIntegrationsRoute
  '/settings': typeof DashboardSettingsRoute
  '/about': typeof MarketingAboutRoute
  '/changelog': typeof MarketingChangelogRoute
  '/contact': typeof MarketingContactRoute
  '/cookie-policy': typeof MarketingCookiePolicyRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/security': typeof MarketingSecurityRoute
  '/terms': typeof MarketingTermsRoute
  '/blog/introducing-envval': typeof BlogIntroducingEnvvalRoute
  '/blog': typeof BlogIndexRoute
  '/repos/$slug': typeof DashboardReposSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/animation': typeof AnimationRoute
  '/extension': typeof ExtensionRoute
  '/home': typeof HomeRoute
  '/og': typeof OgRoute
  '/onboarding': typeof OnboardingRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/device': typeof DashboardDeviceRoute
  '/devices': typeof DashboardDevicesRoute
  '/integrations': typeof DashboardIntegrationsRoute
  '/settings': typeof DashboardSettingsRoute
  '/about': typeof MarketingAboutRoute
  '/changelog': typeof MarketingChangelogRoute
  '/contact': typeof MarketingContactRoute
  '/cookie-policy': typeof MarketingCookiePolicyRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/security': typeof MarketingSecurityRoute
  '/terms': typeof MarketingTermsRoute
  '/blog/introducing-envval': typeof BlogIntroducingEnvvalRoute
  '/blog': typeof BlogIndexRoute
  '/repos/$slug': typeof DashboardReposSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/animation': typeof AnimationRoute
  '/extension': typeof ExtensionRoute
  '/home': typeof HomeRoute
  '/og': typeof OgRoute
  '/onboarding': typeof OnboardingRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/device': typeof DashboardDeviceRoute
  '/_dashboard/devices': typeof DashboardDevicesRoute
  '/_dashboard/integrations': typeof DashboardIntegrationsRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_marketing/about': typeof MarketingAboutRoute
  '/_marketing/changelog': typeof MarketingChangelogRoute
  '/_marketing/contact': typeof MarketingContactRoute
  '/_marketing/cookie-policy': typeof MarketingCookiePolicyRoute
  '/_marketing/privacy': typeof MarketingPrivacyRoute
  '/_marketing/security': typeof MarketingSecurityRoute
  '/_marketing/terms': typeof MarketingTermsRoute
  '/blog/introducing-envval': typeof BlogIntroducingEnvvalRoute
  '/blog/': typeof BlogIndexRoute
  '/_dashboard/repos/$slug': typeof DashboardReposSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/animation'
    | '/extension'
    | '/home'
    | '/og'
    | '/onboarding'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/device'
    | '/devices'
    | '/integrations'
    | '/settings'
    | '/about'
    | '/changelog'
    | '/contact'
    | '/cookie-policy'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/blog/introducing-envval'
    | '/blog'
    | '/repos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/animation'
    | '/extension'
    | '/home'
    | '/og'
    | '/onboarding'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/device'
    | '/devices'
    | '/integrations'
    | '/settings'
    | '/about'
    | '/changelog'
    | '/contact'
    | '/cookie-policy'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/blog/introducing-envval'
    | '/blog'
    | '/repos/$slug'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_dashboard'
    | '/animation'
    | '/extension'
    | '/home'
    | '/og'
    | '/onboarding'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_dashboard/dashboard'
    | '/_dashboard/device'
    | '/_dashboard/devices'
    | '/_dashboard/integrations'
    | '/_dashboard/settings'
    | '/_marketing/about'
    | '/_marketing/changelog'
    | '/_marketing/contact'
    | '/_marketing/cookie-policy'
    | '/_marketing/privacy'
    | '/_marketing/security'
    | '/_marketing/terms'
    | '/blog/introducing-envval'
    | '/blog/'
    | '/_dashboard/repos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  AnimationRoute: typeof AnimationRoute
  ExtensionRoute: typeof ExtensionRoute
  HomeRoute: typeof HomeRoute
  OgRoute: typeof OgRoute
  OnboardingRoute: typeof OnboardingRoute
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingChangelogRoute: typeof MarketingChangelogRoute
  MarketingContactRoute: typeof MarketingContactRoute
  MarketingCookiePolicyRoute: typeof MarketingCookiePolicyRoute
  MarketingPrivacyRoute: typeof MarketingPrivacyRoute
  MarketingSecurityRoute: typeof MarketingSecurityRoute
  MarketingTermsRoute: typeof MarketingTermsRoute
  BlogIntroducingEnvvalRoute: typeof BlogIntroducingEnvvalRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og': {
      id: '/og'
      path: '/og'
      fullPath: '/og'
      preLoaderRoute: typeof OgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension': {
      id: '/extension'
      path: '/extension'
      fullPath: '/extension'
      preLoaderRoute: typeof ExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animation': {
      id: '/animation'
      path: '/animation'
      fullPath: '/animation'
      preLoaderRoute: typeof AnimationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/introducing-envval': {
      id: '/blog/introducing-envval'
      path: '/blog/introducing-envval'
      fullPath: '/blog/introducing-envval'
      preLoaderRoute: typeof BlogIntroducingEnvvalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/terms': {
      id: '/_marketing/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof MarketingTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/security': {
      id: '/_marketing/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof MarketingSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/privacy': {
      id: '/_marketing/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof MarketingPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/cookie-policy': {
      id: '/_marketing/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof MarketingCookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/contact': {
      id: '/_marketing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MarketingContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/changelog': {
      id: '/_marketing/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof MarketingChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/integrations': {
      id: '/_dashboard/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof DashboardIntegrationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/devices': {
      id: '/_dashboard/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DashboardDevicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/device': {
      id: '/_dashboard/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DashboardDeviceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dashboard/repos/$slug': {
      id: '/_dashboard/repos/$slug'
      path: '/repos/$slug'
      fullPath: '/repos/$slug'
      preLoaderRoute: typeof DashboardReposSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardDeviceRoute: typeof DashboardDeviceRoute
  DashboardDevicesRoute: typeof DashboardDevicesRoute
  DashboardIntegrationsRoute: typeof DashboardIntegrationsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardReposSlugRoute: typeof DashboardReposSlugRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardDeviceRoute: DashboardDeviceRoute,
  DashboardDevicesRoute: DashboardDevicesRoute,
  DashboardIntegrationsRoute: DashboardIntegrationsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardReposSlugRoute: DashboardReposSlugRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  AnimationRoute: AnimationRoute,
  ExtensionRoute: ExtensionRoute,
  HomeRoute: HomeRoute,
  OgRoute: OgRoute,
  OnboardingRoute: OnboardingRoute,
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingChangelogRoute: MarketingChangelogRoute,
  MarketingContactRoute: MarketingContactRoute,
  MarketingCookiePolicyRoute: MarketingCookiePolicyRoute,
  MarketingPrivacyRoute: MarketingPrivacyRoute,
  MarketingSecurityRoute: MarketingSecurityRoute,
  MarketingTermsRoute: MarketingTermsRoute,
  BlogIntroducingEnvvalRoute: BlogIntroducingEnvvalRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
